# Local Server
local: true
host: 0.0.0.0
port: 4000
url: "http://localhost:4000/"
url_github_api: "http://localhost:4000/tests/events.json"

# Sub-Repos
include: ["_organization", "_patterns", "_talks"]
