# Site settings
title: Open Source Design
email: core@opensourecedesign.net
description: > # this means to ignore newlines until "baseurl:"
  We are a community of designers and developers aiming to push more
  open design processes and improve the user experience and interface
  design of open source software.

#baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://opensourcedesign.net" # the base hostname & protocol for your site
url_source: "https://github.com/opensourcedesign/opensourcedesign.github.io/blob/master/"
url_edit: "https://edit.opensourcedesign.net/#opensourcedesign/opensourcedesign.github.io/edit/master/"
url_github_api: "https://api.github.com/repos/opensourcedesign/opensourcedesign.github.io/events"

keep_files: [
  "media"
]

include: [
  "_organization",
  "_patterns",
  "_talks"
]

exclude: [
  "_organization/README.md",
  "_patterns/README.md",
  "_posts/events/README.md",
  "_posts/jobs/README.md",
  "_talks/README.md",
  "Gemfile",
  "Gemfile.lock",
  "node_modules/",
  "Rakefile",
  "README.md",
  "sass/",
  "scripts/",
  "vendor/"
]

twitter_username: opensrcdesign
github_username:  opensourcedesign

# Build settings
markdown: kramdown
highlighter: rouge

collections:
  resources:
    output: true
    permalink: /resources/:path/
  people:
    output: true
    permalink: /people/:path/

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: "_posts/articles"
      type: "posts"
    values:
      layout: "post"
      author: "osd"
      category: "articles"
      permalink: /articles/:slug
  -
    scope:
      path: "_posts/events"
      type: "posts"
    values:
      layout: "event"
      category: "events"
      permalink: /events/:year/:month/:slug
  -
    scope:
      path: "_posts/jobs"
      type: "posts"
    values:
      layout: "jobs"
      category: "jobs"
      permalink: /jobs/:year/:slug

permalink: pretty

sass:
    style: compressed
