# Local Server
local: true
host: localhost
port: 4000
url: "http://localhost:4000/"

# Sub-Repos
include: [
    "_posts/events",
    "_posts/jobs",
    "_organization",
    "_patterns",
    "_talks"
]
